############################
# Author: Paul Tribulowski
############################

#This DF represents a acceleration vector in a cartesian coordinate system.

AccelerationComponent x_acceleration	#the x component of the acceleration vector with the associated confidence value.

AccelerationComponent y_acceleration	#the y component of the acceleration vector with the associated confidence value.

AccelerationComponent z_acceleration	#Optional: the z component of the acceleration vector with the associated confidence value.
