############################
# Author: Paul Tribulowski
############################

#This DF represents an acceleration vector in a polar or cylindrical coordinate system.

AccelerationMagnitude acceleration_magnitude	#magnitude of the acceleration vector projected onto the reference plane, with the associated confidence value.

CartesianAngle acceleration_direction		#polar angle of the acceleration vector projected onto the reference plane, with the associated confidence value.

AccelerationComponent z_acceleration		#Optional: the optional z component of the acceleration vector along the reference axis of the cylindrical coordinate system, with the associated confidence value.
